Update distributed-gpu-test-ci.yaml

diff --git a/.github/workflows/distributed-gpu-test-ci.yaml b/.github/workflows/distributed-gpu-test-ci.yaml
--- a/.github/workflows/distributed-gpu-test-ci.yaml
+++ b/.github/workflows/distributed-gpu-test-ci.yaml
@@ -213,36 +213,60 @@ jobs:
         name: Set job output based on previous step
         if: ${{ success() }}
         run: |
+          echo "slurm_status=success"
           echo "slurm_status=success" >> $GITHUB_OUTPUT
 
       - id: set_slurm_status_fail
         name: Set job output on failure
         if: ${{ failure() }}
         run: |
+          echo "slurm_status=failed"
           echo "slurm_status=failed" >> $GITHUB_OUTPUT
+
+      - name: Debug show slurm_status from needs
+          run: |
+            echo "RAW needs.test-on-slurm.outputs.slurm_status: >>>${{ needs.test-on-slurm.outputs.slurm_status }}<<<"
+            echo "as env var:"
+            echo "SLURM_STATUS='${SLURM_STATUS:-}'"
+            printf "len=%s\n" "${#SLURM_STATUS:-0}"
+          env:
+            SLURM_STATUS: ${{ needs.test-on-slurm.outputs.slurm_status }}
             
   publish:
     name: Publish image to GHCR (only if SLURM job success)
     needs: [build, test-on-slurm]
     # if: ${{ needs.test-on-slurm.result == 'success' }}
-    if: ${{ needs['test-on-slurm'].outputs.slurm_status == 'success' }}
+
     runs-on: [self-hosted, docker-host]
-    env:
-      IMAGE_NAME: ghcr.io/dashabalashova/distributed-gpu-test
-      IMAGE_TAG: ${{ needs.build.outputs.image-tag }}
     steps:
-      - name: Ensure image exists locally and push to GHCR
-        env:
-          CR_PAT: ${{ secrets.CR_PAT }}
-        run: |
-          set -euo pipefail
-          TAG="${IMAGE_NAME}:${IMAGE_TAG}"
-          if ! docker image inspect "$TAG" >/dev/null 2>&1; then
-            echo "Image $TAG not found in local docker. Available images:"
-            docker images --format 'table {{.Repository}}\t{{.Tag}}\t{{.ID}}\t{{.Size}}' || true
-            exit 2
-          fi
-          echo "Logging in to ghcr.io"
-          echo "${CR_PAT}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
-          echo "Pushing $TAG"
-          # docker push "$TAG"
+      - name: Debug show slurm_status from needs
+          run: |
+            echo "RAW needs.test-on-slurm.outputs.slurm_status: >>>${{ needs.test-on-slurm.outputs.slurm_status }}<<<"
+            echo "as env var:"
+            echo "SLURM_STATUS='${SLURM_STATUS:-}'"
+            printf "len=%s\n" "${#SLURM_STATUS:-0}"
+          env:
+            SLURM_STATUS: ${{ needs.test-on-slurm.outputs.slurm_status }}
+
+    
+    # if: ${{ needs['test-on-slurm'].outputs.slurm_status == 'success' }}
+    # runs-on: [self-hosted, docker-host]
+    # env:
+    #   IMAGE_NAME: ghcr.io/dashabalashova/distributed-gpu-test
+    #   IMAGE_TAG: ${{ needs.build.outputs.image-tag }}
+    # steps:
+    #   - name: Ensure image exists locally and push to GHCR
+    #     env:
+    #       CR_PAT: ${{ secrets.CR_PAT }}
+    #     run: |
+    #       set -euo pipefail
+    #       TAG="${IMAGE_NAME}:${IMAGE_TAG}"
+    #       if ! docker image inspect "$TAG" >/dev/null 2>&1; then
+    #         echo "Image $TAG not found in local docker. Available images:"
+    #         docker images --format 'table {{.Repository}}\t{{.Tag}}\t{{.ID}}\t{{.Size}}' || true
+    #         exit 2
+    #       fi
+    #       echo "Logging in to ghcr.io"
+    #       echo "${CR_PAT}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
+    #       echo "Pushing $TAG"
+    #       # docker push "$TAG"
