Update distributed-gpu-test-ci.yaml

diff --git a/.github/workflows/distributed-gpu-test-ci.yaml b/.github/workflows/distributed-gpu-test-ci.yaml
--- a/.github/workflows/distributed-gpu-test-ci.yaml
+++ b/.github/workflows/distributed-gpu-test-ci.yaml
@@ -211,24 +211,29 @@ jobs:
   publish:
     name: Publish image to GHCR (only if SLURM job success)
     needs: [build, test-on-slurm]
-    if: ${{ needs.test-on-slurm.result == 'success' }}
-    runs-on: [self-hosted, docker-host]
-    env:
-      IMAGE_NAME: ghcr.io/dashabalashova/distributed-gpu-test
-      IMAGE_TAG: ${{ needs.build.outputs.image-tag }}
     steps:
-      - name: Ensure image exists locally and push to GHCR
-        env:
-          CR_PAT: ${{ secrets.CR_PAT }}
+      - name: Debug needs.status
         run: |
-          set -euo pipefail
-          TAG="${IMAGE_NAME}:${IMAGE_TAG}"
-          if ! docker image inspect "$TAG" >/dev/null 2>&1; then
-            echo "Image $TAG not found in local docker. Available images:"
-            docker images --format 'table {{.Repository}}\t{{.Tag}}\t{{.ID}}\t{{.Size}}' || true
-            exit 2
-          fi
-          echo "Logging in to ghcr.io"
-          echo "${CR_PAT}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
-          echo "Pushing $TAG"
-          # docker push "$TAG"
+          echo "needs.test-on-slurm.result='${{ needs.test-on-slurm.result }}'"
+          echo "needs.build.result='${{ needs.build.result }}'"
+    # if: ${{ needs.test-on-slurm.result == 'success' }}
+    # runs-on: [self-hosted, docker-host]
+    # env:
+    #   IMAGE_NAME: ghcr.io/dashabalashova/distributed-gpu-test
+    #   IMAGE_TAG: ${{ needs.build.outputs.image-tag }}
+    # steps:
+    #   - name: Ensure image exists locally and push to GHCR
+    #     env:
+    #       CR_PAT: ${{ secrets.CR_PAT }}
+    #     run: |
+    #       set -euo pipefail
+    #       TAG="${IMAGE_NAME}:${IMAGE_TAG}"
+    #       if ! docker image inspect "$TAG" >/dev/null 2>&1; then
+    #         echo "Image $TAG not found in local docker. Available images:"
+    #         docker images --format 'table {{.Repository}}\t{{.Tag}}\t{{.ID}}\t{{.Size}}' || true
+    #         exit 2
+    #       fi
+    #       echo "Logging in to ghcr.io"
+    #       echo "${CR_PAT}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
+    #       echo "Pushing $TAG"
+    #       # docker push "$TAG"
